{
  "openapi": "3.0.0",
  "components": {
    "examples": {},
    "headers": {},
    "parameters": {},
    "requestBodies": {},
    "responses": {},
    "schemas": {
      "User": {
        "description": "Model User",
        "properties": {
          "updatedAt": {
            "type": "string",
            "format": "date-time"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "role": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "id": {
            "type": "number",
            "format": "double"
          }
        },
        "required": [
          "updatedAt",
          "createdAt",
          "role",
          "password",
          "email",
          "lastName",
          "firstName",
          "id"
        ],
        "type": "object"
      },
      "GetAllUsersResponse": {
        "properties": {
          "message": {
            "type": "string"
          },
          "users": {
            "items": {
              "$ref": "#/components/schemas/User"
            },
            "type": "array",
            "nullable": true
          }
        },
        "required": [
          "message",
          "users"
        ],
        "type": "object",
        "additionalProperties": false
      },
      "GetUserByIdResponse": {
        "properties": {
          "message": {
            "type": "string"
          },
          "user": {
            "allOf": [
              {
                "$ref": "#/components/schemas/User"
              }
            ],
            "nullable": true
          }
        },
        "required": [
          "message",
          "user"
        ],
        "type": "object",
        "additionalProperties": false
      },
      "CreateUserResponse": {
        "properties": {
          "message": {
            "type": "string"
          }
        },
        "required": [
          "message"
        ],
        "type": "object",
        "additionalProperties": false
      },
      "CreateUserRequest": {
        "properties": {
          "firstName": {
            "type": "string",
            "minLength": 1
          },
          "lastName": {
            "type": "string",
            "minLength": 1
          },
          "email": {
            "type": "string",
            "pattern": "^(.+)@(.+)$"
          },
          "password": {
            "type": "string",
            "minLength": 8
          },
          "role": {
            "type": "string"
          }
        },
        "required": [
          "firstName",
          "lastName",
          "email",
          "password",
          "role"
        ],
        "type": "object",
        "additionalProperties": false,
        "example": {
          "firstName": "John",
          "lastName": "Doe",
          "email": "john.doe@email.com",
          "password": "Password123",
          "role": "User"
        }
      },
      "UpdateUserResponse": {
        "properties": {
          "message": {
            "type": "string"
          }
        },
        "required": [
          "message"
        ],
        "type": "object",
        "additionalProperties": false
      },
      "UpdateUserRequest": {
        "properties": {
          "firstName": {
            "type": "string",
            "minLength": 1
          },
          "lastName": {
            "type": "string",
            "minLength": 1
          },
          "email": {
            "type": "string",
            "pattern": "^(.+)@(.+)$"
          },
          "role": {
            "type": "string"
          }
        },
        "type": "object",
        "additionalProperties": false,
        "example": {
          "firstName": "John",
          "lastName": "Doe",
          "email": "john.doe@email.com",
          "role": "User"
        }
      },
      "DeleteUserResponse": {
        "properties": {
          "message": {
            "type": "string"
          }
        },
        "required": [
          "message"
        ],
        "type": "object",
        "additionalProperties": false
      },
      "Organisation": {
        "description": "Model Organisation",
        "properties": {
          "updatedAt": {
            "type": "string",
            "format": "date-time"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "name": {
            "type": "string"
          },
          "id": {
            "type": "number",
            "format": "double"
          }
        },
        "required": [
          "updatedAt",
          "createdAt",
          "name",
          "id"
        ],
        "type": "object"
      },
      "GetAllOrganisationsResponse": {
        "properties": {
          "message": {
            "type": "string"
          },
          "organisations": {
            "items": {
              "$ref": "#/components/schemas/Organisation"
            },
            "type": "array"
          }
        },
        "required": [
          "message",
          "organisations"
        ],
        "type": "object",
        "additionalProperties": false
      },
      "GetOrganisationByIdResponse": {
        "properties": {
          "message": {
            "type": "string"
          },
          "organisation": {
            "allOf": [
              {
                "$ref": "#/components/schemas/Organisation"
              }
            ],
            "nullable": true
          }
        },
        "required": [
          "message",
          "organisation"
        ],
        "type": "object",
        "additionalProperties": false
      },
      "CreateOrganisationResponse": {
        "properties": {
          "message": {
            "type": "string"
          },
          "organisationID": {
            "type": "number",
            "format": "double",
            "nullable": true
          }
        },
        "required": [
          "message",
          "organisationID"
        ],
        "type": "object",
        "additionalProperties": false
      },
      "CreateOrganisationRequest": {
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "name"
        ],
        "type": "object",
        "additionalProperties": false
      },
      "UpdateOrganisationResponse": {
        "properties": {
          "message": {
            "type": "string"
          }
        },
        "required": [
          "message"
        ],
        "type": "object",
        "additionalProperties": false
      },
      "UpdateOrganisationRequest": {
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          }
        },
        "type": "object",
        "additionalProperties": false
      },
      "DeleteOrganisationResponse": {
        "properties": {
          "message": {
            "type": "string"
          }
        },
        "required": [
          "message"
        ],
        "type": "object",
        "additionalProperties": false
      },
      "GetOrganisationUsersResponse": {
        "properties": {
          "message": {
            "type": "string"
          },
          "users": {
            "items": {
              "$ref": "#/components/schemas/User"
            },
            "type": "array",
            "nullable": true
          }
        },
        "required": [
          "message",
          "users"
        ],
        "type": "object",
        "additionalProperties": false
      },
      "AddUserToOrganisationResponse": {
        "properties": {
          "message": {
            "type": "string"
          }
        },
        "required": [
          "message"
        ],
        "type": "object",
        "additionalProperties": false
      },
      "RemoveUserFromOrganisationResponse": {
        "properties": {
          "message": {
            "type": "string"
          }
        },
        "required": [
          "message"
        ],
        "type": "object",
        "additionalProperties": false
      },
      "Workspace": {
        "properties": {
          "version": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        },
        "required": [
          "version",
          "name"
        ],
        "type": "object"
      },
      "RegisterResponse": {
        "properties": {
          "message": {
            "type": "string"
          },
          "token": {
            "type": "string",
            "nullable": true
          }
        },
        "required": [
          "message",
          "token"
        ],
        "type": "object",
        "additionalProperties": false
      },
      "RegisterRequest": {
        "properties": {
          "firstName": {
            "type": "string",
            "minLength": 1
          },
          "lastName": {
            "type": "string",
            "minLength": 1
          },
          "email": {
            "type": "string",
            "pattern": "^(.+)@(.+)$"
          },
          "password": {
            "type": "string",
            "minLength": 8
          },
          "role": {
            "type": "string"
          }
        },
        "required": [
          "firstName",
          "lastName",
          "email",
          "password",
          "role"
        ],
        "type": "object",
        "additionalProperties": false,
        "example": {
          "firstName": "John",
          "lastName": "Doe",
          "email": "john.doe@email.com",
          "password": "Password123",
          "role": "User"
        }
      },
      "LoginResponse": {
        "properties": {
          "message": {
            "type": "string"
          },
          "token": {
            "type": "string",
            "nullable": true
          }
        },
        "required": [
          "message",
          "token"
        ],
        "type": "object",
        "additionalProperties": false
      },
      "LoginRequest": {
        "properties": {
          "email": {
            "type": "string",
            "pattern": "^(.+)@(.+)$"
          },
          "password": {
            "type": "string",
            "minLength": 8
          }
        },
        "required": [
          "email",
          "password"
        ],
        "type": "object",
        "additionalProperties": false,
        "example": {
          "email": "john.doe@email.com",
          "password": "Password123"
        }
      }
    },
    "securitySchemes": {
      "jwt": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "info": {
    "title": "backend",
    "contact": {}
  },
  "paths": {
    "/users": {
      "get": {
        "operationId": "GetAllUsers",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetAllUsersResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "Get all Users",
        "summary": "Get all Users",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "jwt": []
          }
        ],
        "parameters": []
      },
      "post": {
        "operationId": "CreateUser",
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CreateUserResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "Create and persist a new user.",
        "summary": "Create a new User",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "jwt": []
          }
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUserRequest"
              }
            }
          }
        }
      }
    },
    "/users/{userID}": {
      "get": {
        "operationId": "GetUserById",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetUserByIdResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "Gets a Specific User using their ID",
        "summary": "Get Specific User",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "jwt": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "userID",
            "required": true,
            "schema": {
              "format": "double",
              "type": "number"
            }
          }
        ]
      },
      "patch": {
        "operationId": "UpdateUser",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateUserResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "Update an existing user.",
        "summary": "Update a User",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "jwt": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "userID",
            "required": true,
            "schema": {
              "format": "double",
              "type": "number"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateUserRequest"
              }
            }
          }
        }
      },
      "delete": {
        "operationId": "DeleteUser",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteUserResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "Delete a user.",
        "summary": "Delete a User",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "jwt": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "userID",
            "required": true,
            "schema": {
              "format": "double",
              "type": "number"
            }
          }
        ]
      }
    },
    "/organisations": {
      "get": {
        "operationId": "GetAllOrganisations",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetAllOrganisationsResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "getAllOrganisations",
        "summary": "Get all Organisations",
        "tags": [
          "Organisations"
        ],
        "security": [
          {
            "jwt": []
          }
        ],
        "parameters": []
      },
      "post": {
        "operationId": "CreateOrganisation",
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CreateOrganisationResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "createOrganisation",
        "summary": "Create a new Organisation",
        "tags": [
          "Organisations"
        ],
        "security": [
          {
            "jwt": []
          }
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateOrganisationRequest"
              }
            }
          }
        }
      }
    },
    "/organisations/{orgID}": {
      "get": {
        "operationId": "GetOrganisationById",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetOrganisationByIdResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "getOrganisationById",
        "summary": "Get a specific Organisation",
        "tags": [
          "Organisations"
        ],
        "security": [
          {
            "jwt": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "orgID",
            "required": true,
            "schema": {
              "format": "double",
              "type": "number"
            }
          }
        ]
      },
      "patch": {
        "operationId": "UpdateOrganisation",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateOrganisationResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "updateOrganisation",
        "summary": "Update an existing Organisation",
        "tags": [
          "Organisations"
        ],
        "security": [
          {
            "jwt": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "orgID",
            "required": true,
            "schema": {
              "format": "double",
              "type": "number"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateOrganisationRequest"
              }
            }
          }
        }
      },
      "delete": {
        "operationId": "DeleteOrganisation",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteOrganisationResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "deleteOrganisation",
        "summary": "Delete an existing Organisation",
        "tags": [
          "Organisations"
        ],
        "security": [
          {
            "jwt": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "orgID",
            "required": true,
            "schema": {
              "format": "double",
              "type": "number"
            }
          }
        ]
      }
    },
    "/organisations/{orgID}/users": {
      "get": {
        "operationId": "GetOrganisationUsers",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetOrganisationUsersResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "getOrganisationUsers",
        "summary": "Get all Users within a specific Organisation",
        "tags": [
          "Organisations"
        ],
        "security": [
          {
            "jwt": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "orgID",
            "required": true,
            "schema": {
              "format": "double",
              "type": "number"
            }
          }
        ]
      }
    },
    "/organisations/{orgID}/users/{userID}": {
      "post": {
        "operationId": "AddUserToOrganisation",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddUserToOrganisationResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "addUserToOrganisation",
        "summary": "Add specific User to specific Organisation",
        "tags": [
          "Organisations"
        ],
        "security": [
          {
            "jwt": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "orgID",
            "required": true,
            "schema": {
              "format": "double",
              "type": "number"
            }
          },
          {
            "in": "path",
            "name": "userID",
            "required": true,
            "schema": {
              "format": "double",
              "type": "number"
            }
          }
        ]
      },
      "delete": {
        "operationId": "RemoveUserFromOrganisation",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RemoveUserFromOrganisationResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "removeUserFromOrganisation",
        "summary": "Removes a specific User from a specific Organisation",
        "tags": [
          "Organisations"
        ],
        "security": [
          {
            "jwt": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "orgID",
            "required": true,
            "schema": {
              "format": "double",
              "type": "number"
            }
          },
          {
            "in": "path",
            "name": "userID",
            "required": true,
            "schema": {
              "format": "double",
              "type": "number"
            }
          }
        ]
      }
    },
    "/healthcheck": {
      "get": {
        "operationId": "HealthCheck",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "message"
                  ],
                  "type": "object"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "Health check to ensure server is up and running",
        "summary": "Health Check",
        "tags": [
          "Healthcheck"
        ],
        "security": [],
        "parameters": []
      }
    },
    "/healthcheck/workspaces": {
      "get": {
        "operationId": "GetAllWorkspaces",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "data": {
                      "items": {
                        "$ref": "#/components/schemas/Workspace"
                      },
                      "type": "array"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "data",
                    "message"
                  ],
                  "type": "object"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "Get all Workspaces",
        "summary": "Get all Workspaces",
        "tags": [
          "Healthcheck"
        ],
        "security": [],
        "parameters": []
      }
    },
    "/auth/register": {
      "post": {
        "operationId": "Register",
        "responses": {
          "201": {
            "description": "User Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegisterResponse"
                }
              }
            }
          },
          "422": {
            "description": "Validation Failed"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "register",
        "summary": "Register a new user",
        "tags": [
          "Auth"
        ],
        "security": [],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegisterRequest"
              }
            }
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "operationId": "Login",
        "responses": {
          "200": {
            "description": "Logged In",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "login",
        "summary": "Login a User",
        "tags": [
          "Auth"
        ],
        "security": [],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "/"
    }
  ]
}